name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: ""
        env:
          GPT_API_KEY: ${{ secrets.AI_PLAYGROUND_GPT_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.AI_PLAYGROUND_GEMINI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.AI_PLAYGROUND_CLAUDE_API_KEY }}
          ERNIE_API_KEY: ${{ secrets.AI_PLAYGROUND_ERNIE_API_KEY }}
          ERNIE_SECRET_KEY: ${{ secrets.AI_PLAYGROUND_ERNIE_SECRET_KEY }}
          QWEN_API_KEY: ${{ secrets.AI_PLAYGROUND_QWEN_API_KEY }}
          DALLE_API_KEY: ${{ secrets.AI_PLAYGROUND_DALLE_API_KEY }}
          SD_API_KEY: ${{ secrets.AI_PLAYGROUND_SD_API_KEY }}
